### ISSUE TITLE
better class names

### ISSUE THREAD

**Issue by ritz078** [pleerock/ng2-tabs#9]
`btn` is a very generic name. Any chance that can be changed to something specific to the module as `btn` is in our global CSS and it messes with the CSS of this module. A prefix will be great.

**Comment by pleerock** [comment]
are you using bootstrap?

**Comment by ritz078** [comment]
no. Its our custom CSS.

**Comment by pleerock** [comment]
but this component is used to work with bootstrap, thats why it uses defined in bootstrap classes. If I change them they wont work with bootstrap anymore

**Comment by ritz078** [comment]
oh. I will fork it then. thanks.
